# SniperBot 2.0 Configuration
# This is the main configuration file for the trading bot

[bot]
name = "SniperBot 2.0"
version = "0.1.0"
dry_run = true
paper_trading = true
log_level = "info"

[solana]
# Helius RPC endpoints
rpc_url = "https://mainnet.helius-rpc.com/?api-key=40a78e4c-bdd0-4338-877a-aa7d56a5f5a0"
enhanced_rpc_url = "https://api.helius.xyz/v0/addresses"
commitment = "confirmed"
timeout_seconds = 30

[jupiter]
api_url = "https://quote-api.jup.ag/v6"
swap_url = "https://quote-api.jup.ag/v6/swap"
price_url = "https://price.jup.ag/v4/price"
timeout_seconds = 10
max_retries = 3

[jito]
api_url = "https://mainnet.block-engine.jito.wtf/api/v1"
tip_accounts = [
    "96gYZGLnJYVFmbjzopPSU6QiEV5fGqZNyN9nmNhvrZU5",
    "HFqU5x63VTqvQss8hp11i4wVV8bD44PvwucfZ2bU7gRe",
    "Cw8CFyM9FkoMi7K7Crf6HNQqf4uEMzpKw6QNghXLvLkY",
    "ADaUMid9yfUytqMBgopwjb2DTLSokTSzL1zt6iGPaS49"
]
bundle_timeout_seconds = 30
max_tip_lamports = 50000000  # 0.05 SOL

[exchanges.binance]
enabled = true
api_url = "https://api.binance.com"
websocket_url = "wss://stream.binance.com:9443/ws"
rate_limit_requests_per_minute = 1200

[exchanges.raydium]
enabled = true
api_url = "https://api.raydium.io"
program_id = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"

[exchanges.pumpfun]
enabled = true
api_url = "https://pumpportal.fun/api"
program_id = "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"

[exchanges.meteora]
enabled = true
api_url = "https://dlmm-api.meteora.ag"
program_id = "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo"

[risk_management]
max_position_size_usd = 1000.0
max_daily_loss_usd = 500.0
max_drawdown_percent = 10.0
stop_loss_percent = 5.0
take_profit_percent = 20.0
max_slippage_bps = 300  # 3%

[risk_management.position_limits]
max_positions = 5
max_exposure_per_token_percent = 20.0
min_liquidity_usd = 10000.0

[strategies.pumpfun_sniping]
enabled = true
confidence_threshold = 0.7
max_market_cap_usd = 1000000.0
min_volume_24h_usd = 50000.0
bonding_curve_threshold = 0.8

[strategies.liquidity_sniping]
enabled = true
confidence_threshold = 0.6
min_liquidity_usd = 100000.0
max_age_hours = 24.0
min_apr_percent = 50.0

[analytics]
python_executables_path = "./pyinstaller_executables"
talib_binary = "talib_analyzer"
social_scanner_binary = "social_scanner"
sentiment_analyzer_binary = "sentiment_analyzer"

[logging]
level = "info"
file_path = "./logs/sniperbot.log"
max_file_size_mb = 100
max_files = 10

[monitoring]
metrics_enabled = true
metrics_port = 9090
health_check_port = 8080

# WebSocket Configuration for Real-Time Data
[websocket]
enabled = true
helius_ws_url = "wss://atlas-mainnet.helius-rpc.com/?api-key=${HELIUS_API_KEY}"
binance_ws_url = "wss://stream.binance.com:9443/ws"
reconnect_timeout_seconds = 5
max_retries = 10
ping_interval_seconds = 30

# WebSocket Subscriptions
[[websocket.subscriptions]]
subscription_type = "PriceUpdates"
symbol = "SOL/USDC"
enabled = true

[[websocket.subscriptions]]
subscription_type = "NewTokens"
enabled = true

[[websocket.subscriptions]]
subscription_type = "WhaleAlerts"
enabled = true

[trading]
initial_balance = 10000.0
analysis_interval_seconds = 60
max_concurrent_trades = 5
default_position_size = 100.0
enable_live_trading = false

# AI Decision Engine Configuration
[ai]
enabled = true
api_key = "XbhYfsLJ1kx8XoAjcutmhz6qjxWStf1Y"
model = "mistral-large-latest"
temperature = 0.3
top_p = 0.95
tool_use_enabled = true
